apiVersion: v1
kind: Service
metadata:
  name: ghost-content-svc
  labels:
    app: ghost-content
spec:
  ports:
  - nodePort: 32368
    port: 2368
    protocol: TCP
    targetPort: 2368
  selector:
    app: ghost-content
    tier: ghost-content
  type: NodePort
---
kind: PersistentVolume
apiVersion: v1
metadata:
  name: ghost-content-volume
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/Users/fran9992/Dev/2ghost/content"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ghost-content-pvc
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
---
apiVersion: apps/v1beta2 # for versions before 1.8.0 use apps/v1beta1
kind: Deployment
metadata:
  name: ghost-content
  labels:
    app: ghost-content
spec:
  selector:
    matchLabels:
      app: ghost-content
      tier: ghost-content
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: ghost-content
        tier: ghost-content
    spec:
      containers:
      - image: ghost
        name: ghost-content
        ports:
        - containerPort: 2368
          name: ghost-port
        volumeMounts:
        - name: ghost-content-pvc
          mountPath: /var/lib/ghost/content
      volumes:
      - name: ghost-content-pvc
        persistentVolumeClaim:
          claimName: ghost-content-pvc
